// Code generated by tygo. DO NOT EDIT.

//////////
// source: admin.go

export interface ApiInviteUserRequest {
  email: string;
}

//////////
// source: chat.go

export interface ApiChatRequest {
  query: string;
  history: {
    user: string;
    assistant: string;
  }[];
}

//////////
// source: controllers.go


//////////
// source: feedback.go

export interface ApiFeedbackRequest {
  feedback: string;
}

//////////
// source: oauth.go

export interface GoogleUser {
  email: string;
  family_name: string;
  given_name: string;
  id: string;
  locale: string;
  name: string;
  picture: string;
  verified_email: boolean;
}

//////////
// source: search.go

export interface ApisearchRequest {
  query: string;
  searchQuery: string;
  history: {
    user: string;
    assistant: string;
  }[];
}

//////////
// source: stats.go

export interface ApiStatsRequest {
  From: string /* RFC3339 */;
  To: string /* RFC3339 */;
}
