// Code generated by tygo. DO NOT EDIT.

//////////
// source: organisation.go

export interface Organisation {
  id: string;
  Name: string;
  Users: User[];
}

//////////
// source: user.go

export interface UserChatRequest {
  ID: number /* uint */;
  CreatedAt: string /* RFC3339 */;
  UpdatedAt: string /* RFC3339 */;
  Deleted: any /* gorm.DeletedAt */;
  UserId: string;
  Request: string;
  Response: string;
}
export interface UserFeedback {
  ID: number /* uint */;
  CreatedAt: string /* RFC3339 */;
  Feedback: string;
  UserId: string;
}
export interface User {
  id: string;
  Name: string;
  Email: string;
  Password: string;
  Organisations: Organisation[];
  ChatRequests: UserChatRequest[];
  IsAdmin: boolean;
  InvitationPending: boolean;
  Deleted: any /* gorm.DeletedAt */;
  Feedback: UserFeedback[];
}
